### PR TITLE
Authentication buttons

### PR DESCRIPTION
**Pull request by tomasmcm**
https://trello.com/c/8y7rTYdQ/4-add-signup-login-and-logout-buttons
Adds component with authentication trigger button (sign in and sing out)

Base for https://trello.com/c/sZISoUAB/2-integrate-with-authentication-service

### CODE REVIEW

**Review by ruimagalhaes — COMMENTED** [review]
@tomasmcm can you explain the motivation behind the AUTHENTICATION_SERVER config? Thanks!

**Comment by tomasmcm** [comment]
@ruimagalhaes the idea was to use it as a feature flag. This way we don't break compatibility with upstream.
Now that you added a new FIREBASE var, it probably makes more sense to change this var to a boolean (and in lowerCase) 🤔

**Comment by ruimagalhaes** [comment]
@tomasmcm I'm not sure that we need the flag but for now we can go with it I believe. The component will need to have the firebase context to control the user interaction. For now I'll link the button with the Google signup only

**Comment by tomasmcm** [comment]
@ruimagalhaes the idea was to have one config that would toggle all user authentication related stuff (sign in / out buttons, profile page, ...). We can tweak this to use the same for this and to save the firebase data, but for now I believe this is fine.

**Review by ruimagalhaes — APPROVED** [review]

**Pull request merged**
