### PR TITLE
Favorites on firebase

### PR DESCRIPTION
**Pull request by ruimagalhaes**
- https://trello.com/c/vnyNhUlJ

Had to change some HOC to include firebase checks and and the favorites panel was changed to use firebase instead of the storage when the user is logged.

### CODE REVIEW

**Review by tomasmcm — APPROVED** [review]
Tested and seems to work fine 👌. However, this approach is not very scalable. We are continuing to change a lot of files to add firebase as a replacement for localstorage.

Did a quick search and found this library JS-data that provides adapters for several storage options (https://www.js-data.io/docs/js-data-firebase https://www.js-data.io/docs/js-data-localstorage). I believe something like this would be better for future digitransit as it allows even more options (mongodb, sql, redis) without much changes needed later on.
Might be worth taking a look at and possibly refactor once all new features are done

**Comment by ruimagalhaes** [comment]
> Tested and seems to work fine 👌. However, this approach is not very scalable. We are continuing to change a lot of files to add firebase as a replacement for localstorage.
> 
> Did a quick search and found this library JS-data that provides adapters for several storage options (https://www.js-data.io/docs/js-data-firebase https://www.js-data.io/docs/js-data-localstorage). I believe something like this would be better for future digitransit as it allows even more options (mongodb, sql, redis) without much changes needed later on.
> Might be worth taking a look at and possibly refactor once all new features are done

@tomasmcm  I agree with the fact that the changes we are adding are not that elegant but I don't know, at this moment, how can we improve this using the existing store/localstorage/relay setup. What I've been doing is a 'as basic as I can' firebase gate in front of the data accesses that we know.

**Comment by tomasmcm** [comment]
> @tomasmcm I agree with the fact that the changes we are adding are not that elegant but I don't know, at this moment, how can we improve this using the existing store/localstorage/relay setup. What I've been doing is a 'as basic as I can' firebase gate in front of the data accesses that we know.

@ruimagalhaes ok, but you understand that if someone wants to use something else instead of firebase they would need to mess with every file again. Just wondering if we could add something more valuable and scalable (that would also have higher chances of being merged back with digitransit)

**Comment by ruimagalhaes** [comment]
@tomasmcm I do understand that and I'm not happy with placing a log of firebase accesses when we need but at this moment I don't know how to handle this in a better way because the accesses to firebase and the other stores are fundamentally different. Like you said, maybe we can take another look at this when we have all the features implemented

**Pull request merged**
