### PR TITLE
User data on the Profile Page

### PR DESCRIPTION
**Pull request by ruimagalhaes**
- Profile page is now using user data from firebase
- Signout and destroy account redirects user to the main page
- Download data functionality was not done since we need to hook it up with the database usage. A new card was added for that
- @tomasmcm should we add a popup for the user to confirm that the account should really be deleted?

### CODE REVIEW

**Comment by tomasmcm** [comment]
@ruimagalhaes added a dropdown on the navbar, a confirmation before deleting the account, and a notification after. Please review 😄 

Also, I noticed an error when trying to delete the account if I had not just signed in (in between server refreshes). Not sure if it's critical, but it's worth investigating. Ultimately we can just add a notification asking to sign out and in again
```
L {code: "auth/requires-recent-login", message: "This operation is sensitive and requires recent au…ation. Log in again before retrying this request."}
code: "auth/requires-recent-login"
message: "This operation is sensitive and requires recent authentication. Log in again before retrying this request."
```

**Comment by ruimagalhaes** [comment]
> @ruimagalhaes added a dropdown on the navbar, a confirmation before deleting the account, and a notification after. Please review 😄
> 
> Also, I noticed an error when trying to delete the account if I had not just signed in (in between server refreshes). Not sure if it's critical, but it's worth investigating. Ultimately we can just add a notification asking to sign out and in again
> 
> ```
> L {code: "auth/requires-recent-login", message: "This operation is sensitive and requires recent au…ation. Log in again before retrying this request."}
> code: "auth/requires-recent-login"
> message: "This operation is sensitive and requires recent authentication. Log in again before retrying this request."
> ```

@tomasmcm good catch! do we have any sort of popup to do this or can we go with a simple alert for now?

**Comment by ruimagalhaes** [comment]
@tomasmcm I guess we can use the same alert that you introduced for the delete account confirmation

**Comment by ruimagalhaes** [comment]
@tomasmcm added a component for the dialog so we can use it anywhere and used it for the error that you pointed

**Comment by tomasmcm** [comment]
@ruimagalhaes 👍on the reusable dialog, but I think it may be overkill for the information about signing out and in again, can we just use a message?
```
this.context.executeAction(addMessage, {
  persistence: 'repeat',
  content: {
    en: [{ type: 'text', content: 'This operation is sensitive and requires recent authentication. Log in again before retrying this request.' }],
  },
});
```

**Comment by ruimagalhaes** [comment]
@tomasmcm got it, changed that. thanks for the suggestion!

**Review by tomasmcm — APPROVED** [review]

**Pull request merged**
